# Generated by Django 5.1.7 on 2025-04-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="مهارت")),
            ],
        ),
        migrations.CreateModel(
            name="UserSkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coach", "مربی"),
                            ("vet", "دامپزشک"),
                            ("gym_owner", "باشگاه\u200cدار"),
                            ("shop_owner", "فروشگاه\u200cدار"),
                            ("user", "کاربر عادی"),
                            ("expert", "کارشناس"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="نقش کاربر",
                    ),
                ),
                (
                    "demands",
                    models.ManyToManyField(
                        related_name="demanded_by",
                        to="account.skill",
                        verbose_name="تقاضاها",
                    ),
                ),
                (
                    "offers",
                    models.ManyToManyField(
                        related_name="offered_by",
                        to="account.skill",
                        verbose_name="عرضه\u200cها",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
