# Generated by Django 5.1.7 on 2025-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_skill_userskillprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "مهارت", "verbose_name_plural": "مهارت ها"},
        ),
        migrations.AlterModelOptions(
            name="userskillprofile",
            options={"verbose_name": "پروفایل", "verbose_name_plural": "پروفایل ها"},
        ),
        migrations.AlterField(
            model_name="userskillprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "هیچکدام"),
                    ("coach", "مربی"),
                    ("vet", "دامپزشک"),
                    ("gym_owner", "باشگاه/استبل"),
                    ("shop_owner", "فروشنده/فروشگاه"),
                    ("expert", "کارشناس"),
                ],
                default="user",
                max_length=20,
                verbose_name="نقش کاربر",
            ),
        ),
    ]
