# Generated by Django 5.1.7 on 2025-03-13 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("age", models.IntegerField(verbose_name="سن")),
                ("breed", models.CharField(max_length=255, verbose_name="نژاد")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("image", models.ImageField(upload_to="horses/", verbose_name="عکس")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. اسب ها",
                "verbose_name_plural": "اسب",
            },
        ),
    ]
