# Generated by Django 5.1.7 on 2025-03-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horse",
            options={"verbose_name": "اسب", "verbose_name_plural": "1. اسب ها"},
        ),
    ]
