# Generated by Django 5.1.7 on 2025-03-13 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت شروع"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="شروع مزایده")),
                ("end_time", models.DateTimeField(verbose_name="پایان مزایده")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="وضعیت مزایده",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ساخته شده توسط",
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.horse",
                        verbose_name="اسب",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. مزایده ها",
                "verbose_name_plural": "مزایده",
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان مزایده"),
                ),
                (
                    "is_winner",
                    models.BooleanField(default=False, verbose_name="برنده مزایده"),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auction_module.auction",
                        verbose_name="مزایده",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پیشنهاد توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. پیشنهاد ها",
                "verbose_name_plural": "پیشنهاد",
            },
        ),
    ]
