# Generated by Django 5.1.7 on 2025-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"verbose_name": "مزایده", "verbose_name_plural": "1. مزایده ها"},
        ),
        migrations.AlterModelOptions(
            name="bid",
            options={"verbose_name": "پیشنهاد", "verbose_name_plural": "2. پیشنهاد ها"},
        ),
        migrations.AlterField(
            model_name="auction",
            name="start_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="حذاقل پیشنهاد"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("closed", "بسته"),
                    ("pending", "در انتظار تایید"),
                ],
                default="open",
                max_length=10,
                verbose_name="وضعیت مزایده",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="قیمت پیشنهادی"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
        ),
    ]
