# Generated by Django 5.1.7 on 2025-03-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0002_alter_auction_options_alter_bid_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ("-amount",),
                "verbose_name": "پیشنهاد",
                "verbose_name_plural": "2. پیشنهاد ها",
            },
        ),
    ]
