# Generated by Django 5.1.7 on 2025-04-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0003_alter_bid_options"),
        ("core", "0002_alter_horse_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="horse_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="سن"),
        ),
        migrations.AddField(
            model_name="auction",
            name="horse_breed",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نژاد"
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="horse_description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="auction",
            name="horse_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="horses/", verbose_name="عکس"
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="horse_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.horse",
                verbose_name="اسب",
            ),
        ),
    ]
