# Generated by Django 5.1.7 on 2025-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0004_auction_horse_age_auction_horse_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="horse_age",
            field=models.IntegerField(default=None, verbose_name="سن"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_breed",
            field=models.CharField(default=None, max_length=255, verbose_name="نژاد"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_description",
            field=models.TextField(default=None, verbose_name="توضیحات"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_image",
            field=models.ImageField(
                default=None, upload_to="horses/", verbose_name="عکس"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_name",
            field=models.CharField(default=None, max_length=255, verbose_name="نام"),
            preserve_default=False,
        ),
    ]
