# Generated by Django 5.1.7 on 2025-04-09 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_module",
            "0005_alter_auction_horse_age_alter_auction_horse_breed_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ساخته شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "باز"),
                    ("closed", "بسته"),
                    ("pending", "در انتظار تایید"),
                ],
                default="open",
                max_length=10,
                null=True,
                verbose_name="وضعیت مزایده",
            ),
        ),
    ]
