# Generated by Django 5.1.7 on 2025-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0006_alter_auction_created_by_alter_auction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="start_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="حداقل مبلغ مزایده"
            ),
        ),
    ]
