# Generated by Django 5.1.7 on 2025-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0007_alter_auction_start_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="horse_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="سن"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_breed",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نژاد"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="horses/", verbose_name="عکس"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام"
            ),
        ),
    ]
