# Generated by Django 5.1.7 on 2025-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_module",
            "0008_alter_auction_horse_age_alter_auction_horse_breed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="horse_age",
            field=models.IntegerField(null=True, verbose_name="سن"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_breed",
            field=models.CharField(max_length=255, null=True, verbose_name="نژاد اسب"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_description",
            field=models.TextField(null=True, verbose_name="درباره اسب"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_image",
            field=models.ImageField(
                null=True, upload_to="horses/", verbose_name="عکس اسب"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="horse_name",
            field=models.CharField(max_length=255, null=True, verbose_name="نام اسب"),
        ),
    ]
