# Generated by Django 5.1.7 on 2025-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_module",
            "0009_alter_auction_horse_age_alter_auction_horse_breed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="horse_summary",
            field=models.CharField(
                blank=True, max_length=55, null=True, verbose_name="خلاصه درباره اسب"
            ),
        ),
    ]
