# Generated by Django 5.1.7 on 2025-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0010_auction_horse_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="horse_video",
            field=models.FileField(
                blank=True, null=True, upload_to="horses/", verbose_name="ویدئو اسب"
            ),
        ),
    ]
