# Generated by Django 5.1.7 on 2025-11-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0011_auction_horse_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={
                "ordering": ("-start_time",),
                "verbose_name": "مزایده",
                "verbose_name_plural": "1. مزایده ها",
            },
        ),
    ]
