# Generated by Django 5.1.7 on 2025-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0012_alter_auction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="horse_doc",
            field=models.FileField(
                blank=True, null=True, upload_to="horses/", verbose_name="مدارک اسب"
            ),
        ),
    ]
