# Generated by Django 5.1.7 on 2025-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0013_auction_horse_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="horse_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("thoroughbred", "اصیل"),
                    ("quarter", "کوارتر"),
                    ("arabian", "عربی"),
                    ("mustang", "موستانگ"),
                    ("other", "سایر"),
                ],
                max_length=20,
                null=True,
                verbose_name="دسته\u200cبندی اسب",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="price_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "اقتصادی (زیر ۱۰۰ میلیون)"),
                    ("medium", "متوسط (۱۰۰-۵۰۰ میلیون)"),
                    ("premium", "پریمیوم (۵۰۰ میلیون - ۱ میلیارد)"),
                    ("luxury", "لوکس (بالای ۱ میلیارد)"),
                ],
                max_length=20,
                null=True,
                verbose_name="دسته\u200cبندی قیمت",
            ),
        ),
    ]
