# Generated by Django 5.2.7 on 2025-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_module", "0014_auction_horse_category_auction_price_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="horse_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("thoroughbred", "اصیل انگلیسی"),
                    ("arabian", "اسب عربی"),
                    ("quarter", "کوارتر"),
                    ("appaloosa", "آپالوسا"),
                    ("paint", "پینت"),
                    ("andalusian", "آندالوسی"),
                    ("friesian", "فریزیان"),
                    ("hanoverian", "هانووری"),
                    ("akhal_teke", "آخال تکه"),
                    ("mustang", "موستانگ"),
                    ("other", "سایر"),
                ],
                max_length=20,
                null=True,
                verbose_name="نژاد اسب",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="price_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "اقتصادی (زیر ۱۰۰ میلیون)"),
                    ("medium", "متوسط (۱۰۰-۵۰۰ میلیون)"),
                    ("premium", "پریمیوم (۵۰۰ میلیون - ۱ میلیارد)"),
                    ("luxury", "لوکس (بالای ۱ میلیارد)"),
                ],
                max_length=20,
                null=True,
                verbose_name="محدوده قیمت",
            ),
        ),
    ]
