# Generated by Django 5.1.7 on 2025-03-17 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام باشگاه")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(upload_to="gyms/", verbose_name="تصویر باشگاه"),
                ),
                ("location", models.CharField(max_length=500, verbose_name="آدرس")),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل باشگاه",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="وب\u200cسایت"),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ساعات کاری"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gyms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک باشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "باشگاه",
                "verbose_name_plural": "باشگاه\u200cها",
            },
        ),
    ]
