# Generated by Django 5.1.7 on 2025-04-10 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GymSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_info",
                    models.CharField(
                        max_length=255, verbose_name="اطلاعات سانس (روز، تاریخ، ساعت)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="gym_module.gym",
                        verbose_name="باشگاه مربوطه",
                    ),
                ),
                (
                    "reserved_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reserved_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رزرو شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "سانس باشگاه",
                "verbose_name_plural": "سانس\u200cهای باشگاه",
            },
        ),
    ]
