# Generated by Django 5.1.7 on 2025-04-12 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="عنوان")),
                ("summary", models.CharField(max_length=255, verbose_name="خلاصه")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="کلمات کلیدی",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="blog/", verbose_name="تصویر اصلی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "منتشر شده"), ("d", "چک نویس")],
                        max_length=5,
                        verbose_name="وضعیت انتشار",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "1. مقالات",
                "ordering": ("-publish_time",),
            },
        ),
    ]
