# Generated by Django 5.1.7 on 2025-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=1, upload_to="product_images/", verbose_name="تصویر محصول"
            ),
            preserve_default=False,
        ),
    ]
