# Generated by Django 5.1.7 on 2025-04-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_module", "0003_order_orderdetail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created",),
                "verbose_name": "سفارش",
                "verbose_name_plural": "2. سفارشات",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "محصول",
                "verbose_name_plural": "1. محصولات",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام فروشگاه")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(upload_to="shops/", verbose_name="تصویر فروشگاه"),
                ),
                ("location", models.CharField(max_length=500, verbose_name="آدرس")),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل باشگاه",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="وب\u200cسایت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروشگاه",
                "verbose_name_plural": "3. فروشگاه ها",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shop_module.shop",
                verbose_name="فروشنده",
            ),
        ),
    ]
