# Generated by Django 5.1.7 on 2025-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_module", "0004_alter_order_options_alter_product_options_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="contact_number",
            field=models.CharField(max_length=20, null=True, verbose_name="شماره تماس"),
        ),
    ]
