# Generated by Django 5.1.7 on 2025-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_module", "0005_alter_shop_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.BigIntegerField(default=0, verbose_name="قیمت"),
        ),
    ]
